# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c126092f1e9e7344902551ec2860adab9e8be0cffeba1c5237ffe1cf230235d13934aa5056ca8e9255ec12f46b2b83633273bb235e7c1c7e9821d6513ee93a40

test:
  secret_key_base: efc782d3bbda6154fefea01914595196933d36f24ce0ffb57102b2614b29e6d57ec43e39c9ff817cab0de68a34a21511034081819f67eb4898ef0c17fc12ad24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
